version: "3.1"

services:
  llama_index_api:
    image: llama-index-api:latest
    container_name: llama_index_api
    environment:
      - FLASK_APP=src/main.py
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    ports:
      - "5000:5000"
    networks:
      - network

networks:
  network:
    driver: bridge
